nohup: ignoring input
2019-11-21 16:52:15 js-104-67.jetstream-cloud.org augur[17535] INFO Booting broker and its manager...
2019-11-21 16:52:16 js-104-67.jetstream-cloud.org augur[17535] INFO Booting housekeeper...
2019-11-21 16:52:16 js-104-67.jetstream-cloud.org root[17535] INFO Starting update processes...
2019-11-21 16:52:16 js-104-67.jetstream-cloud.org augur[17535] INFO Starting server...
[2019-11-21 16:52:16 -0600] [17535] [INFO] Starting gunicorn 19.9.0
[2019-11-21 16:52:16 -0600] [17535] [INFO] Listening at: http://0.0.0.0:5000 (17535)
[2019-11-21 16:52:16 -0600] [17535] [INFO] Using worker: sync
[2019-11-21 16:52:16 -0600] [17594] [INFO] Booting worker with pid: 17594
[2019-11-21 16:52:16 -0600] [17595] [INFO] Booting worker with pid: 17595
[2019-11-21 16:52:16 -0600] [17596] [INFO] Booting worker with pid: 17596
[2019-11-21 16:52:16 -0600] [17597] [INFO] Booting worker with pid: 17597
2019-11-21 16:52:18 js-104-67.jetstream-cloud.org root[17589] INFO Housekeeper spawned repo_info model updater process for repo 1 with PID 17589
2019-11-21 16:52:18 js-104-67.jetstream-cloud.org root[17590] INFO Housekeeper spawned commits model updater process for repo 1 with PID 17590
2019-11-21 16:52:18 js-104-67.jetstream-cloud.org root[17593] INFO Housekeeper spawned insights model updater process for repo 1 with PID 17593
2019-11-21 16:52:18 js-104-67.jetstream-cloud.org root[17592] INFO Housekeeper spawned contributors model updater process for repo 1 with PID 17592
2019-11-21 16:52:18 js-104-67.jetstream-cloud.org root[17588] INFO Housekeeper spawned issues model updater process for repo 25430 with PID 17588
2019-11-21 16:52:18 js-104-67.jetstream-cloud.org root[17591] INFO Housekeeper spawned pull_requests model updater process for repo 1 with PID 17591
[2019-11-21 16:52:25 -0600] [17683] [INFO] Booting worker with pid: 17683
[2019-11-21 16:52:25 -0600] [17684] [INFO] Booting worker with pid: 17684
[2019-11-21 16:52:25 -0600] [17535] [INFO] Handling signal: hup
[2019-11-21 16:52:25 -0600] [17535] [INFO] Hang up: Master
[2019-11-21 16:52:25 -0600] [17685] [INFO] Booting worker with pid: 17685
[2019-11-21 16:52:25 -0600] [17686] [INFO] Booting worker with pid: 17686
[2019-11-21 16:52:25 -0600] [17688] [INFO] Booting worker with pid: 17688
[2019-11-21 16:52:25 -0600] [17687] [INFO] Booting worker with pid: 17687
[2019-11-21 16:52:25 -0600] [17684] [INFO] Worker exiting (pid: 17684)
2019-11-21 16:52:25 js-104-67.jetstream-cloud.org augur[17684] INFO Shutting down app updates...
2019-11-21 16:52:25 js-104-67.jetstream-cloud.org augur[17684] INFO Finalizing config...
2019-11-21 16:52:25 js-104-67.jetstream-cloud.org augur[17684] INFO Shutting down housekeeper updates...
2019-11-21 16:52:25 js-104-67.jetstream-cloud.org augur[17684] INFO Killing main augur process with PID: 17684
[2019-11-21 16:52:25 -0600] [17683] [INFO] Worker exiting (pid: 17683)
2019-11-21 16:52:25 js-104-67.jetstream-cloud.org augur[17683] INFO Shutting down app updates...
2019-11-21 16:52:25 js-104-67.jetstream-cloud.org augur[17683] INFO Finalizing config...
2019-11-21 16:52:25 js-104-67.jetstream-cloud.org augur[17683] INFO Shutting down housekeeper updates...
2019-11-21 16:52:25 js-104-67.jetstream-cloud.org augur[17683] INFO Killing main augur process with PID: 17683
2019-11-21 18:43:20 js-104-67.jetstream-cloud.org augur.server[17686] ERROR Exception on /api/unstable/repo-groups/22/repos/21334/top-committers [GET]
Traceback (most recent call last):
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jcv3m4/augur-team/augur/server.py", line 368, in generated_function
    data = self.transform(func, args, kwargs)
  File "/home/jcv3m4/augur-team/augur/server.py", line 312, in transform
    data = func(*args, **kwargs)
  File "/home/jcv3m4/augur-team/augur/metrics/contributor/contributor.py", line 407, in top_committers
    total_commits = int(results.iloc[0]['sum'])
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2019-11-21 18:43:20 js-104-67.jetstream-cloud.org augur.server[17685] ERROR Exception on /api/unstable/repo-groups/22/top-committers [GET]
Traceback (most recent call last):
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jcv3m4/augur-team/augur/server.py", line 368, in generated_function
    data = self.transform(func, args, kwargs)
  File "/home/jcv3m4/augur-team/augur/server.py", line 312, in transform
    data = func(*args, **kwargs)
  File "/home/jcv3m4/augur-team/augur/metrics/contributor/contributor.py", line 407, in top_committers
    total_commits = int(results.iloc[0]['sum'])
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2019-11-21 18:43:59 js-104-67.jetstream-cloud.org augur.server[17687] ERROR Exception on /api/unstable/repo-groups/22/repos/21334/top-committers [GET]
Traceback (most recent call last):
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jcv3m4/augur-team/augur/server.py", line 368, in generated_function
    data = self.transform(func, args, kwargs)
  File "/home/jcv3m4/augur-team/augur/server.py", line 312, in transform
    data = func(*args, **kwargs)
  File "/home/jcv3m4/augur-team/augur/metrics/contributor/contributor.py", line 407, in top_committers
    total_commits = int(results.iloc[0]['sum'])
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2019-11-21 18:43:59 js-104-67.jetstream-cloud.org augur.server[17686] ERROR Exception on /api/unstable/repo-groups/22/top-committers [GET]
Traceback (most recent call last):
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jcv3m4/augur-team/augur/server.py", line 368, in generated_function
    data = self.transform(func, args, kwargs)
  File "/home/jcv3m4/augur-team/augur/server.py", line 312, in transform
    data = func(*args, **kwargs)
  File "/home/jcv3m4/augur-team/augur/metrics/contributor/contributor.py", line 407, in top_committers
    total_commits = int(results.iloc[0]['sum'])
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2019-11-21 18:44:30 js-104-67.jetstream-cloud.org augur.server[17686] ERROR Exception on /api/unstable/repo-groups/22/repos/21334/top-committers [GET]
Traceback (most recent call last):
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jcv3m4/augur-team/augur/server.py", line 368, in generated_function
    data = self.transform(func, args, kwargs)
  File "/home/jcv3m4/augur-team/augur/server.py", line 312, in transform
    data = func(*args, **kwargs)
  File "/home/jcv3m4/augur-team/augur/metrics/contributor/contributor.py", line 407, in top_committers
    total_commits = int(results.iloc[0]['sum'])
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2019-11-21 18:44:30 js-104-67.jetstream-cloud.org augur.server[17687] ERROR Exception on /api/unstable/repo-groups/22/top-committers [GET]
Traceback (most recent call last):
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jcv3m4/augur-team/augur/server.py", line 368, in generated_function
    data = self.transform(func, args, kwargs)
  File "/home/jcv3m4/augur-team/augur/server.py", line 312, in transform
    data = func(*args, **kwargs)
  File "/home/jcv3m4/augur-team/augur/metrics/contributor/contributor.py", line 407, in top_committers
    total_commits = int(results.iloc[0]['sum'])
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2019-11-21 18:44:58 js-104-67.jetstream-cloud.org augur.server[17688] ERROR Exception on /api/unstable/repo-groups/22/repos/21334/top-committers [GET]
Traceback (most recent call last):
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jcv3m4/augur-team/augur/server.py", line 368, in generated_function
    data = self.transform(func, args, kwargs)
  File "/home/jcv3m4/augur-team/augur/server.py", line 312, in transform
    data = func(*args, **kwargs)
  File "/home/jcv3m4/augur-team/augur/metrics/contributor/contributor.py", line 407, in top_committers
    total_commits = int(results.iloc[0]['sum'])
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2019-11-21 18:44:58 js-104-67.jetstream-cloud.org augur.server[17685] ERROR Exception on /api/unstable/repo-groups/22/top-committers [GET]
Traceback (most recent call last):
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jcv3m4/augur-team/augur/server.py", line 368, in generated_function
    data = self.transform(func, args, kwargs)
  File "/home/jcv3m4/augur-team/augur/server.py", line 312, in transform
    data = func(*args, **kwargs)
  File "/home/jcv3m4/augur-team/augur/metrics/contributor/contributor.py", line 407, in top_committers
    total_commits = int(results.iloc[0]['sum'])
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2019-11-21 18:45:05 js-104-67.jetstream-cloud.org augur.server[17687] ERROR Exception on /api/unstable/repo-groups/22/repos/21334/top-committers [GET]
Traceback (most recent call last):
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jcv3m4/augur-team/augur/server.py", line 368, in generated_function
    data = self.transform(func, args, kwargs)
  File "/home/jcv3m4/augur-team/augur/server.py", line 312, in transform
    data = func(*args, **kwargs)
  File "/home/jcv3m4/augur-team/augur/metrics/contributor/contributor.py", line 407, in top_committers
    total_commits = int(results.iloc[0]['sum'])
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2019-11-21 18:45:05 js-104-67.jetstream-cloud.org augur.server[17687] ERROR Exception on /api/unstable/repo-groups/22/top-committers [GET]
Traceback (most recent call last):
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jcv3m4/augur-team/augur/server.py", line 368, in generated_function
    data = self.transform(func, args, kwargs)
  File "/home/jcv3m4/augur-team/augur/server.py", line 312, in transform
    data = func(*args, **kwargs)
  File "/home/jcv3m4/augur-team/augur/metrics/contributor/contributor.py", line 407, in top_committers
    total_commits = int(results.iloc[0]['sum'])
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2019-11-21 18:46:07 js-104-67.jetstream-cloud.org augur.server[17688] ERROR Exception on /api/unstable/repo-groups/22/repos/21334/top-committers [GET]
Traceback (most recent call last):
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jcv3m4/augur-team/augur/server.py", line 368, in generated_function
    data = self.transform(func, args, kwargs)
  File "/home/jcv3m4/augur-team/augur/server.py", line 312, in transform
    data = func(*args, **kwargs)
  File "/home/jcv3m4/augur-team/augur/metrics/contributor/contributor.py", line 407, in top_committers
    total_commits = int(results.iloc[0]['sum'])
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2019-11-21 18:46:07 js-104-67.jetstream-cloud.org augur.server[17687] ERROR Exception on /api/unstable/repo-groups/22/top-committers [GET]
Traceback (most recent call last):
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jcv3m4/project4/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jcv3m4/augur-team/augur/server.py", line 368, in generated_function
    data = self.transform(func, args, kwargs)
  File "/home/jcv3m4/augur-team/augur/server.py", line 312, in transform
    data = func(*args, **kwargs)
  File "/home/jcv3m4/augur-team/augur/metrics/contributor/contributor.py", line 407, in top_committers
    total_commits = int(results.iloc[0]['sum'])
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
